server.port=8080

spring.application.name=Plant-Growth-Tracking

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.url=jdbc:mariadb://localhost/plant_growth_tracking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

jwt.secret=a3f6d0e9c4b2f1a9e8c7d6b5a4f3e2d1b0c9e8f7a6b5c4d3e2f1a0b9c8d7e6

weather.api.key=8457b6d6c5e8c460744084ef2483c4d2
weather.api.url=https://api.openweathermap.org/data/2.5/weather

groq.api.key=${GROQ_API_KEY:your_groq_key_here}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama3-8b-8192